/**
 * Build the per-recipient landing URL that replaces {{onsite_url}}.
 *
 * Starts from the sender's `landing_url`, appends ONLY allowlisted UTM query
 * values from `attribution` (everything else is dropped), and carries the sm_t
 * token in the fragment (`#sm_t=<token>`). The fragment is never sent to a
 * server on navigation, so the token reaches only the recipient's browser,
 * which then presents it to POST /api/onsite/redeem. No nonce is placed in the
 * URL — the visitor nonce is generated by the browser at redeem time.
 */

import { UTM_ATTRIBUTION_MAP } from "./config.js";

export function buildLandingUrl(
  landingUrl: string,
  attribution: Partial<Record<keyof typeof UTM_ATTRIBUTION_MAP, string>>,
  token: string
): string {
  const url = new URL(landingUrl);
  for (const [key, parameter] of Object.entries(UTM_ATTRIBUTION_MAP)) {
    const value = attribution[key as keyof typeof UTM_ATTRIBUTION_MAP];
    if (typeof value === "string" && value.length > 0) {
      url.searchParams.set(parameter, value);
    }
  }
  url.hash = `sm_t=${token}`;
  return url.toString();
}
