/**
 * Secret material for onsite: the 256-bit sm_t activation token and the opaque
 * session cookie value.
 *
 * The plaintext of each secret lives only in transit (the landing_url fragment
 * or the cookie); the DB stores nothing but its SHA-256 hex hash. Lookups hash
 * the presented value and match on the hash column, so a database leak never
 * yields a usable token or session. Gating comparisons use a constant-time
 * compare. The visitor nonce is generated by the browser, not here.
 */

import { createHash, randomBytes, timingSafeEqual } from "node:crypto";

/** Random 256-bit token, base64url (43 chars) — the `sm_t` in the URL fragment. */
export function generateActivationToken(): string {
  return randomBytes(32).toString("base64url");
}

/** Opaque 256-bit session cookie value. */
export function generateSessionSecret(): string {
  return randomBytes(32).toString("base64url");
}

/** SHA-256 hex — the value stored and matched on for every secret. */
export function hashSecret(value: string): string {
  return createHash("sha256").update(value).digest("hex");
}

/** Constant-time equality for two SHA-256 hex strings. */
export function hashesEqual(a: string, b: string): boolean {
  const bufA = Buffer.from(a, "utf8");
  const bufB = Buffer.from(b, "utf8");
  if (bufA.length !== bufB.length) return false;
  return timingSafeEqual(bufA, bufB);
}
