/**
 * Startup auto-migrator: clients attach a DB via env and deploy — no CLI step.
 * Migrations are generated by `pnpm db:generate` into drizzle/{sqlite,mysql,pg}/
 * and MUST ship with the app (the Dockerfile copies drizzle/ into the image).
 */

import { existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { migrate as migrateSqlite } from "drizzle-orm/better-sqlite3/migrator";
import { migrate as migrateMysql } from "drizzle-orm/mysql2/migrator";
import { migrate as migratePg } from "drizzle-orm/node-postgres/migrator";
import type { DispatcherDb } from "./client.js";

const DIALECT_DIRS = { sqlite: "sqlite", mysql: "mysql", postgres: "pg" } as const;

export function resolveMigrationsDir(dialect: DispatcherDb["dialect"]): string {
  const moduleDir = dirname(fileURLToPath(import.meta.url));
  // src/db/ and dist/db/ are both two levels below the repo/app root.
  const candidates = [
    resolve(moduleDir, "../../drizzle", DIALECT_DIRS[dialect]),
    resolve(moduleDir, "../../../drizzle", DIALECT_DIRS[dialect]),
    resolve(process.cwd(), "drizzle", DIALECT_DIRS[dialect]),
  ];
  for (const candidate of candidates) {
    if (existsSync(join(candidate, "meta", "_journal.json"))) return candidate;
  }
  throw new Error(
    `Dispatcher state-DB migrations not found for dialect "${dialect}". ` +
      `Looked in: ${candidates.join(", ")}. ` +
      "The drizzle/ directory must be deployed alongside the app (check the Docker image / working directory)."
  );
}

export async function runDispatcherMigrations(dbx: DispatcherDb): Promise<void> {
  const migrationsFolder = resolveMigrationsDir(dbx.dialect);
  if (dbx.dialect === "sqlite") {
    migrateSqlite(dbx.db, { migrationsFolder });
    return;
  }
  if (dbx.dialect === "mysql") {
    await migrateMysql(dbx.db, { migrationsFolder });
    return;
  }
  await migratePg(dbx.db, { migrationsFolder });
}
